title: Experimental Sounds Finland
description:
  A calendar for experimental sound events in Finland
author:
  name: Â© Libero Mureddu & Andrea Mancianti
baseurl: ""
url: experimentalsoundingfinland.github.io
remote_theme: jekyll/minima
header_pages:
  - index.md
  - calendar.md
  - eventadd.md
  - contact.md
minima:
skin: auto

